title: Karson Sommer
email: karson-sommer@uiowa.edu
description: > # this means to ignore newlines until "baseurl:"
  Karson Sommer
# social links
#github_username: karsonkevin2 # DO NOT include the @ character, or else the build will fail!
languages:
  First-Choice:
    - MATLAB
  Project Experience:
    - Java
    - C
    - SQL
  Class Experience:
    - C++
    - Python
    - Assembly
    - R
    - VHDL
    - Verilog
  Minor Exposure:
    - JavaScript
    - HTML

show_excerpts: true # set to false to remove excerpts on the homepage

theme: jekyll-theme-dinky
