title: Karson Sommer
author: Karson Sommer
email: karson-sommer@uiowa.edu
description: Overview of selected projects

google_analytics:
 
# social links
github_username: karsonkevin2 # DO NOT include the @ character, or else the build will fail!

show_excerpts: true # set to false to remove excerpts on the homepage

theme: jekyll-theme-dinky
